[template]
src   = "elasticsearch.yml"
dest  = "/opt/elasticsearch/config/elasticsearch.yml"
owner = "root"
group = "root"
mode  = "0755"
keys = [
  "/elasticsearch/config",
  "/elasticsearch_api",
  "/elasticsearch_transport",
]
check_cmd = "/app/bin/check {{ .src }}"
