[template]
src   = "output_elasticsearch.conf"
dest  = "/opt/logstash/conf.d/output_elasticsearch.conf"
owner = "root"
group = "root"
mode  = "0755"
keys = [
  "/logstash/config",
  "/elasticsearch_api"
]
check_cmd = "/app/bin/check {{ .src }}"
